<script>
    window.onload = function() {
        document.body.id="managementCss";
        date_heure('date_heure');
    };
</script>

            <div class="span12">
                <div class="pagination-centered well">
                    <legend><h3>Add a new scenario</h3></legend>
                    <p>Please fill the form</p>

                </div>
                <div  class="row-fluid">
                    <div class="span4 offset4">
<!--                        <h2>All the information</h2>-->


                        <div class ="well pagination-centered">

                            <form action="/Profile/scenariovalide" method="post" onsubmit="return validateFormNewScenar()">
                                <fieldset>
                                    <legend>Enter your information</legend>

                                    <label><strong>Scenario Name</strong></label>
                                    <div id="ErrorScenarName">
                                        <input class ="input" type="text" placeholder="Scenario Name..." id="scenario_name" name = "name" >
                                    </div>

                                    <label><strong>Description</strong></label>
                                    <div id="ErrorDesc">
                                        <textarea rows="3" class="" id="description" name="desc"></textarea>
                                    </div>
                                    
                                    <div class="control-group">
                                        <label class="control-label" for="select01"><strong>Controller</strong></label>
                                        <div class="controls">
                                            <?php
                                                //$ii = 0;

                                                if (isset($controllers) and ($controllers != "")) {
                                                    $control = true;
                                                    echo '<select id="selectCont" name="formCont" onChange="changeMoves(this.form);">Select your controller';
                                                    echo '<option selected="selected">Select your controller</option>';
                                                    foreach ($controllers as $controller) {
                                                        echo '<option>' . $controller->getName() . '</option>';
                                                    }
                                                    echo '</select>';
                                                }
                                                else
                                                {
                                                    echo 'No Controllers available';
                                                    $move = false;
                                                }
                                                ?> 
                                        </div>
                                    </div>
                                    
                                    <div class="control-group">  
                                        <label class="control-label" for="select01"><strong>Choose the associated movement</strong></label>  
                                        <div class="controls">  
                                            
                                                <?php
                                                $ii = 0;
                                               
                                                $move = true;
                                                if (isset($movements)) {
                                                    echo '<select id="select01Move" name="formMouvement">';
                                                }
                                                else
                                                {
                                                    echo '<select id="select01Move" name="formMouvement" style="display: none;">';
                                                    $move = false;
                                                }
                                                echo '</select>';
                                                ?>                                           
                                        </div> 
                                    </div> 

                                    <input type="hidden" value="0" id="theValue" /><br>
                                    <a  class="btn" id="addactionbutton" onclick="add_action()" > Add action</a>
                                    <a  class="btn btn-danger" onclick="delete_action()" > Delete action</a>
                                    <div class="control-group" id="actions_zone"><br>
                                    </div>
                                    <div class="control-group" id="movements_zone">
                                    </div><br>
<!--                                    <br><a  class="btn btn-danger btn-large" onclick="delete_action()" > Delete action</a>-->
                                    <div id="displaybuttons">
                                        <?php
                                        if($move)
                                           echo '<input type="submit" class="btn btn-success btn-large" value="Validate">';
                                        else
                                             echo '<a  class="btn  btn-warning btn-large" href="/Profile/home">Go Back</a>';
                                        ?>
                                    </div>
                                </fieldset>
                            </form>
                        </div>

                    </div>
                </div> 
            </div>

        </div>
    </div>

