<script>
    window.onload = function() {
        document.body.id="managementCss";
        date_heure('date_heure');
    };
</script>

<!--<span id="date_heure"></span>-->

<div class="span12">

    <div class="well pagination-centered">
        <legend><h3>Management page</h3></legend>
        <p>Here you can edit your information, create or delete your scenarios and movements...</p>
        <a class="btn btn-large" href="/API/settings">Settings</a>
    </div>

    
        <div class="span6" style="margin:0">
            <div class="well pagination-centered">
                
                <legend><h4>All your information</h4></legend>

                <div id="info" >
<!--                      <p>Name: <?php echo $member->getName(); ?></p>
                    <p>Age: <?php echo $member->getAdult(); ?></p>-->

                    <div  class="row-fluid">
                    <table class="table table-bordered table-striped">
                        <tr class="info">
                            <td><strong><div class="pagination-centered">Name</div></strong></td>
                            <td><strong><div class="pagination-centered">Age</div></strong></td>
                        </tr>

                        <tr>
                            <td><div class="pagination-centered"><?php echo $member->getName(); ?></div></td>
                            <td><div class="pagination-centered"><?php echo $member->getAdult(); ?></div></td>
                        </tr>
                    </table>
                    </div>

                    <a class="btn btn-large" onclick="ShowEdit()">Edit</a>


                    <!-- Edit Form --> 
                    <form id="form_edit"  method="post"  style="display:none" action="/profile/ajInfo" >
                        <fieldset>

                            <br><div class="span6" style="margin:0">
                                <!-- Name field --> 
                                <div class="span3" style="margin:0">
                                    <label>Name</label>
                                    <div id="ErrorNameUser">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-user"></i></span>
                                            <input class ="input input-medium" type="text" value="<?php echo $member->getName(); ?>" id="Name" name = "Name" >
                                        </div>
                                    </div>
                                </div>

                                <!-- Password field -->
                                <div class="span3" style="margin:0">
                                    <label>New Password</label>
                                    <div id="ErrorPswd1">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-lock"></i></span>
                                            <input class ="input input-medium" type="text" placeholder="<?php echo $member->getPassword(); ?>" id="Pswd1" name = "Pswd1" >

                                        </div>
                                    </div>
                                </div>  


                            </div>



                            <div class="span6" style="margin:0">

                                <!-- Age checkbox -->                                                                                     
                                <div class="span3" style="margin:0">
                                    <label>Age</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-font"></i></span>
                                            <select class="input-medium" id="select01" name="formAge">
                                                <option <?php if ($member->getAdult() == "adult") echo 'selected="selected"' ?>>adult</option>
                                                <option <?php if ($member->getAdult() == "child") echo 'selected="selected"' ?>>child</option>
                                            </select>  
                                        </div>
                                    </div>
                                </div>

                                <!-- Repeated password field -->
                                <div class="span3" style="margin:0">
                                    <label>Repeat password</label>
                                    <div id="ErrorPswd2">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-lock"></i></span>
                                            <input class ="input input-medium" type="text"  placeholder="<?php echo $member->getPassword(); ?>" id="Pswd2" name = "Pswd2" >

                                        </div>
                                    </div>
                                </div>


                            </div>


                            <!-- Update button --> 
                            <!--<a  class="btn btn-success btn-large" onclick="validateFormEdit()">Update</a>-->
                        </fieldset>
                        <br><input class="btn btn-success btn-large" type="submit" value="Update" id="submit_form_btn"/>
                    </form>
                </div>
                
            </div>

            <!-- OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO -->    

            <div class="movements well">
                <legend class="pagination-centered"><h4>List of movements</h4></legend>
                <?php
                echo '<table class="table table-hover table-bordered">';
                
                echo'
                <tr class="info">
                <td><strong><div class="pagination-centered">Movement</div></strong></td>
                <td><strong><div class="pagination-centered">Scenario</div></strong></td>
                </tr>';
                foreach ($member->getMovements() as $mov) {
                    $j = 0;
                    echo '<tr>';
                    echo '<td>';
                    echo $mov->getDesc();
                    echo '</td>';
                    echo '<td>';
                    foreach ($member->getScenarios() as $scen) {
                        
                        $mov2 = $scen->getMovement();
                        {
                            if ($mov2->getDesc() == $mov->getDesc()) {
                                echo $scen->getName();
                                $j++;
                            }
                        }
                    }
                    if ($j == 0)
                        echo 'No scenario';
                }
                echo '</td>';
                echo '</tr>';
                echo '</table>';
                ?>
            </div>


            <!-- OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO -->    



        </div>

        <!-- list of scenarios -->
        <div class="span6">
            <!-- OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO -->    
            <div class ="well">
                <!-- display of related list scenario -->    
                <?php
                echo ' <div class="pagination-centered"><legend><h4>List of scenarios related to ' . $member->getName() . ' </h4></legend></div>';

                 #<!-- link to scenario creation page -->
                echo'<div class="pagination-centered"><p><a class="btn btn-primary btn-large" href="/profile/creerscenario">Add a scenario &raquo;</a></p></div><br>';
                
                $i = 0;
                foreach ($member->getScenarios() as $scen) {
                    $i++;

                    echo '<a  class="btn" onclick="actionscenario(' . $i . ')"> ' . $scen->getName() . '</a>';
                    echo'<div id="bouton_' . $i . '"style="display:none">';
                    echo '<a class="btn btn-danger" href="/profile/deleteScenario?id=' . $scen->getId() . '">Delete scenario</a>';
                    echo '<a class="btn btn-warning" onclick="changeMovesEdit('.$scen->getId().');">Edit scenario</a>';               
                    echo '<table class="table table-hover"    ';


                    //display titles of lines 
                    echo '<tr>';
                    echo "<th>Scenario</th>";
                    echo "<th>Scenario's description</th>";
                    echo "<th>Movement</th>";
                    echo "<th>Associated actions</th>";
                    echo "<th>Action's desription</th>";
                    echo "<th>Actuator</th>";
                    echo '</tr>';

                    //display of scenario name (nomScenario), desciprtion of scenario (descriptionScenario), scenario movement (mouvementScenario)
                    echo '<tr><td> ' . $scen->getName() . '</td>';
                    echo '<td> ' . $scen->getDesc() . '</td>';
                    echo '<td> ' . $scen->getMovement()->getName() . '</td>';

                    //loop about actions: name, description, actuators
                    $j = 0;
                    foreach ($scen->getActions() as $action) {
                        if ($j == 2) {
                            echo '<tr><td></td>';
                            echo '<td></td>';
                            echo '<td></td>';
                        }
                        echo '<td>' . $action->getName() . '</td>';
                        echo '<td>' . $action->getDesc() . '</td>';
                        echo '<td>' . $action->getActuator() . '</td>';
                        echo '</tr>';
                        $j = 2;
                    }
                    echo '</tr>';
                    echo '</table>';
                    echo '</div>';
                    echo'<br>';
                    
                }
                ?>
            </div>
            <!-- OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO -->    
            <a class="btn btn-primary btn-large" href="/Profile/controlkinect">Control Kinect</a>
            <a class="btn btn-primary btn-large" href="/Profile/controlmicro">Control Microphone</a>
            <a class="btn btn-primary btn-large" href="/Profile/controlbracelet">Control Bracelet</a>

        </div>
    </div>

</div>
</div>

<script type="text/javascript">
                        $(document).ready(function() {
                            $("body").on('click', "#submit_form_btn", function(e) {
                                if (validateFormEdit()) {
                                    e.preventDefault();

                                    $.ajax({
                                        type: "post",
                                        url: $("#form_edit").attr('action'),
                                        data: $("#form_edit").serialize(),
                                        success: function(result) {
                                            $("#info").html(result);
                                        },
                                        error: function() {
                                            alert('Une erreur est survenue !')
                                        }
                                    });
                                }
                            });
                        });

                        $("body").on('submit', "#form_edit", function() {

                            var ret = true;
                            ret = validateFormEdit();
                            return ret;

                        });
</script>
