<script>
    window.onload = function() {
        document.body.id="managementCss";
        date_heure('date_heure');
    };
</script>

<div class="span4 offset4">
    <div class="hero-unit">
        <h1 class="pagination-centered ">Log In</h1>

        <!-- log in form -->
        <form action="/management/signin" method="post" onsubmit="return validateForm()">
            <fieldset>
                <legend class="pagination-centered">Enter your name and password</legend>

                <!-- name field --> 
                <label>Name</label>
                <div id="ErrorName">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <input type="text" placeholder="Your name"  id="Name" name= "name" >
                    </div>
                </div>
                <br>
                <!-- password field --> 
                <label>Password</label>
                <div id="ErrorPswd1">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input type="password" placeholder="Your password" id="Pswd1" name="pass">
                    </div>
                </div>

                <span class="help-block" id="error"></span>

                <!-- log in button --> 
                <div class="pagination-centered" >
                    <br><button type="submit" class="btn btn-primary btn-large">Log In &raquo;</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
</div>
</div>
